permalink: none
auto: true
pygments: true
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

production_url : http://wafiq.github.com
title : Code Blog

author :
  name : Wafiq Rodzuan
  email : wafiqrodzuan@gmail.com
  github : wafiq
  twitter : wfxyz
  tagline : Do things
